run:
  concurrency: 4
  timeout: 1m
  tests: false
  issues-exit-code: 0
output:
  format: colored-line-number

issues:
  exclude-use-default: false

linters-settings:
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 300
  errcheck:
    check-blank: true
  govet:
    enable:
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - deepequalerrors
      - errorsas
      - fieldalignment

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - godot
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace